name: My Target Workflow

on:
  repository_dispatch:
    types: [trigger-workflow]

  workflow_dispatch:
    inputs:
      target_service:
        description: 'Input tag in lowercase (e.g., taste)'
        required: true

permissions:
  contents: read
  actions: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Service Name
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            service_name="${{ github.event.inputs.target_service }}"
          else
            service_name="${{ github.event.client_payload.service }}"
          fi
          echo "Service Name: $service_name"
          echo "service_name=$service_name" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Allure CLI
        run: |
          npm install -g allure-commandline --save-dev

      - name: Run tests
        id: pytest
        run: |
          if [ "$service_name" = "ALL" ]; then
            pytest --alluredir=results/allure --junitxml=reports/junit.xml
          else
            pytest -m "$service_name" --alluredir=results/allure --junitxml=reports/junit.xml
          fi

      - name: Generate Allure Report
        if: always()
        run: | 
          allure generate results/allure --clean -o allure-report

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.ALLURE_SECRET }} 
            publish_dir: ./allure-report
            publish_branch: allure-report
            keep_files: false

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: ./reports/junit.xml
