name: My Target Workflow

on:
  repository_dispatch:
    types: [trigger-workflow]

  workflow_dispatch:
    inputs:
      target_service:
        description: 'Input tag in lowercase (e.g., taste)'
        required: true

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Service Name
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            service_name="${{ github.event.inputs.target_service }}"
          else
            service_name="${{ github.event.client_payload.service }}"
          fi
          echo "Service Name: $service_name"
          echo "service_name=$service_name" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Allure CLI
        run: |
          npm install -g allure-commandline --save-dev

      - name: Run tests
        id: pytest
        run: |
          if [ "$service_name" = "ALL" ]; then
            pytest --alluredir=results/allure --junitxml=reports/junit.xml
          else
            pytest -m "$service_name" --alluredir=results/allure --junitxml=reports/junit.xml
          fi

      - name: Generate Allure Report
        if: always()
        run: | 
          allure generate results/allure --clean -o allure-report

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: ./reports/junit.xml

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: allure-report
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: results/allure

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: allure-report
          publish_dir: allure-history
